snyk/snyk-maven-plugin

- pom.xml
- src/it/multi-module/.snyk
- src/it/multi-module/child-module/pom.xml
- src/it/multi-module/pom.xml
- src/it/multi-module/verify.bsh
- src/main/java/io/snyk/maven/plugins/SnykMonitor.java
- src/main/java/io/snyk/maven/plugins/SnykPolicy.java
- src/main/java/io/snyk/maven/plugins/SnykTest.java
The plugin now reads Snyk policy files and sends their contents to the server-side for processing.
> feat: policy file

- pom.xml
- src/it/multi-module/.snyk
- src/it/multi-module/pom.xml
- src/it/multi-module/verify.bsh
- src/it/single-module/pom.xml
- src/it/single-module/verify.bsh
- src/main/java/io/snyk/maven/plugins/Constants.java
- src/main/java/io/snyk/maven/plugins/SnykMonitor.java
- src/main/java/io/snyk/maven/plugins/SnykPolicy.java
- src/main/java/io/snyk/maven/plugins/SnykTest.java
(1) NPE when project.getBaseDir() returns null
(2) update .snyk policy file so that policies expire in a hundred years
> fix: NPE in project basedir; updated snyk policy file

- README.md
Updating the README.md to point to version 1.1.1
> docs: version update to 1.1.1

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> chore: Adding in issue, contributing and pr template

- pom.xml
- src/it/multi-module/pom.xml
- src/it/single-module/pom.xml
> feat: bumping snyk plugin version

- README.md
> docs: close build tag in installation example

- .travis.yml
- src/it/private-repo-module/pom.xml
- src/it/private-repo-module/verify.bsh
- src/main/java/io/snyk/maven/plugins/ProjectTraversal.java
- src/main/java/io/snyk/maven/plugins/SnykMonitor.java
- src/main/java/io/snyk/maven/plugins/SnykTest.java
This PR fixes issue with unresolved dependencies and private Maven repositories.
Originally only Maven Central repository was created and configured to resolve dependencies (project or plugin). Now we use builtin Maven parameters injected by Maven plugin manager.
#28
I see some code duplication between `SnykTest.java` and `SnykMonitor.java`, but currently it's not the scope of this ticket, so we can refactor it later.
> fix: support private repositories

- pom.xml
- src/it/multi-module/pom.xml
- src/it/private-repo-module/pom.xml
- src/it/single-module/pom.xml
Bumping up plugin version for publishing
> bumpint up plugin version

- .travis.yml
> feat: Add java 9 to the tests matrix

- README.md
- pom.xml
- src/main/java/io/snyk/maven/plugins/SnykMonitor.java
- src/main/java/io/snyk/maven/plugins/SnykTest.java
Pull in the contributions from @sfat 
- Added travis and snyk badges
- Removed some unnecessary exceptions in the methods declarations
https://github.com/snyk/snyk-maven-plugin/pull/38
https://github.com/snyk/snyk-maven-plugin/pull/41
> Add badges + remove unused exceptions

- pom.xml
- src/it/multi-module/pom.xml
- src/it/private-repo-module/pom.xml
- src/it/single-module/pom.xml
- src/main/java/io/snyk/maven/plugins/HttpClientHelper.java
- src/main/java/io/snyk/maven/plugins/SnykMonitor.java
- src/main/java/io/snyk/maven/plugins/SnykTest.java
Fix for #24, in supporting of proxy set through `~/.m2/settings.xml`
Yes
https://github.com/snyk/snyk-maven-plugin/pull/40
https://github.com/snyk/snyk-maven-plugin/issues/24
> feat: Support for proxy server settings in ~/.m2/settings.xml

- src/main/java/io/snyk/maven/plugins/Constants.java
Clone of https://github.com/snyk/snyk-maven-plugin/pull/21
> Constants should be non-instantiable

- README.md
- pom.xml
- src/it/settings.xml
- src/main/java/io/snyk/maven/plugins/Constants.java
- src/main/java/io/snyk/maven/plugins/SnykMonitor.java
- src/main/java/io/snyk/maven/plugins/SnykTest.java
See PR #64. Merged from internal branch to run integration tests correctly.
> feat: fail on auth error

- src/it/remediation/pom.xml
- src/it/remediation/verify.bsh
- src/main/java/io/snyk/maven/plugins/SnykTest.java
- [ x] Ready for review
- [ x] Follows [CONTRIBUTING](https://github.com/snyk/snyk-maven-plugin/blob/master/CONTRIBUTING.md) rules
- [ x] Reviewed by Snyk internal team
Adds remediation advise with Snyk test output
SnykTest
Nothing, it test "remediation" included
Remediation advise is what makes this just as valuable as the CLI
> Feat: adding remediation advise after 'snyk test'

- pom.xml
- src/it/multi-module/verify.bsh
- src/it/settings.xml
- src/main/java/io/snyk/maven/plugins/SnykTest.java
This PR logs request payload on debug level on snyk test command.
> feat: log request payload on debug level when run test mojo

- pom.xml
#Fix #83 
Set a plugin version.
It is a very simple change
Run any maven goal and see whether the build process works fine 
N/A
N/A
N/A
N/A
> Set Maven Compile Plugin version

- README.md
- pom.xml
- src/it/settings.xml
- src/main/java/io/snyk/maven/plugins/SnykMonitor.java
- src/main/java/io/snyk/maven/plugins/SnykTest.java
Closes #79 
Sets both configuration and CLI option to skip the plugin execution.
Simple changes in SnykMonitor and SnykTest to add the functionality
Executing the plugin with the <skip> configuration parameter on the project's pom or
using the CLI option -Dsnyk.skip (just as predisposed in #79's expected behaviour)
N/A
N/A
N/A
N/A
> Option <skip>true|false</skip>

- .github/workflows/test.yml
- pom.xml
Adds a basic GitHub Actions workflow to build and test the new Maven plugin
> Add basic test workflow

- .idea/codeStyles/Project.xml
Adds IntelliJ formatting rules so we can share the same code format.
> chore: add intellij formatting rules

- .idea/codeStyles/Project.xml
- src/it/test-multi-module-child/child-module-1/pom.xml
- src/it/test-multi-module-child/child-module-2/pom.xml
- src/it/test-multi-module-child/invoker.properties
- src/it/test-multi-module-child/pom.xml
- src/it/test-multi-module-child/verify.groovy
- src/it/test-multi-module-parent/child-module-1/pom.xml
- src/it/test-multi-module-parent/child-module-2/pom.xml
- src/it/test-multi-module-parent/invoker.properties
- src/it/test-multi-module-parent/pom.xml
- src/it/test-multi-module-parent/verify.groovy
Tests for multi-module support in new Maven plugin. It current requires `--all-projects` at parent-level, otherwise, only the child is tested.
> test: multi-module support for v2

- src/it/test-with-dependency/invoker.properties
- src/it/test-with-dependency/pom.xml
- src/it/test-with-dependency/verify.groovy
- src/it/test-with-ignores/.snyk
- src/it/test-with-ignores/invoker.properties
- src/it/test-with-ignores/pom.xml
- src/it/test-with-ignores/verify.groovy
Added a test scenario to make sure a project with a .snyk file is picked up. And to counter one without a .snyk file which should detect vulnerabilities.
> test: ensure .snyk file is picked up for v2

- pom.xml
> Release process v2

- src/it/monitor-with-dependency/invoker.properties
- src/it/monitor-with-dependency/pom.xml
- src/it/monitor-with-dependency/verify.groovy
- src/main/java/io/snyk/snyk_maven_plugin/SnykMonitorMojo.java
Added `monitor` goal which runs `snyk monitor`.
> feat: add monitor goal

- src/it/test-and-monitor/invoker.properties
- src/it/test-and-monitor/pom.xml
- src/it/test-and-monitor/verify.groovy
Added test scenario to ensure both test and monitor goals work together with different configuration. In this case, test is skipped while monitor isn't.
> test: ensure multiple executions work together

- .idea/codeStyles/Project.xml
- README.md
Updated docs to be more linear and only mention features supported in current v2.
> docs: update readme for v2 release

- .github/workflows/test.yml
- README.md
- pom.xml
- src/it/test-update-policy-always/invoker.properties
- src/it/test-update-policy-always/pom.xml
- src/it/test-update-policy-always/setup.groovy
- src/it/test-update-policy-always/verify.groovy
- src/it/test-update-policy-never/invoker.properties
- src/it/test-update-policy-never/pom.xml
- src/it/test-update-policy-never/setup.groovy
- src/it/test-update-policy-never/verify.groovy
- src/it/test-with-invalid-cli-executable/pom.xml
- src/it/test-with-specific-cli-version/pom.xml
- src/it/test-with-specific-cli-version/setup.groovy
- src/main/java/io/snyk/snyk_maven_plugin/download/CLIVersions.java
- src/main/java/io/snyk/snyk_maven_plugin/download/ExecutableDownloader.java
- src/main/java/io/snyk/snyk_maven_plugin/download/UpdatePolicy.java
- src/main/java/io/snyk/snyk_maven_plugin/goal/SnykMojo.java
- src/main/java/io/snyk/snyk_maven_plugin/goal/SnykMojoExecutor.java
- src/test/java/io/snyk/snyk_maven_plugin/download/CLIVersionsTest.java
- src/test/java/io/snyk/snyk_maven_plugin/download/UpdatePolicyTest.java
- src/test/java/io/snyk/snyk_maven_plugin/it/ITUtils.java
Adds support for `updatePolicy` and ensures `version` is always updated.
> feat: support update policy for downloading cli

- README.md
> docs: prepare README for v2 release

- README.md
Mention default phases so people know when goals are executed by default.
> docs: mention default phases for each goal

- pom.xml
- src/main/java/io/snyk/snyk_maven_plugin/download/ExecutableDownloader.java
We are not using Jodd so we don't need to include it.
> chore: remove unused jodd deps

- README.md
Update README
Trivial
Not
Previous example 1.149.0 gives a java.io.IOException: Server returned HTTP response code: 403 for URL: https://static.snyk.io/cli/v1.149.0/snyk-macos 
This example works
> docs: update version example. Previous version example gave a 403

- src/main/java/io/snyk/snyk_maven_plugin/download/ExecutableDownloader.java
Resolves the `latest` version to an actual version by fetching `https://static.snyk.io/cli/latest/version`. Then we download and verify that specific version.
This way, if the version of the binary download tagged as `latest` does not correspond to the version of the sha256 file tagged as `latest` (by bad luck caused by time to update various things like S3 and CDN caches, etc), we don't end up failing because fail to validate version x of a binary against version y of a sha256.
> Get specific version for 'latest' and download/verify that

- CONTRIBUTING.md
Adds documentation for manual release process.
> docs: document release process [ROAD-1230]
