.snyk
Adds an initial snyk policy to ignore an EPL license issue. The maven plugin is an open-sourced project and this license type is ok to use.
=> chore: add snyk policy to ignore a license issue

README.md, pom.xml, src/it/multi-module/pom.xml, src/it/private-repo-module/pom.xml, src/it/single-module/pom.xml, src/main/java/io/snyk/maven/plugins/ProjectTraversal.java, src/main/java/io/snyk/maven/plugins/SnykMonitor.java, src/main/java/io/snyk/maven/plugins/SnykTest.java
This PR adds a new configuration parameter to include dependencies with provided scope.
The parameter name is `includeProvidedDependencies` with default value `true`, so we don't break existing behavior.
Example configuration
```
...
configuration>
<apiToken>${env.MY_SNYK_TOKEN}</apiToken>
<failOnSeverity>low</failOnSeverity>
<includeProvidedDependencies>false</includeProvidedDependencies>
</configuration>
...
```
=> feat: include provided dependencies into project traversal via config parameter

pom.xml
Partially revert of #53. We still use `plexus-utils` without vulnerabilities, but don't update `maven-core` because of breaking changes.
=> fix: plexus utils dependency

README.md, pom.xml, src/it/license-issues-module/pom.xml, src/it/license-issues-module/verify.bsh, src/it/settings.xml, src/main/java/io/snyk/maven/plugins/SnykTest.java
This PR fix following issues:
- use field `packageName` instead of `moduleName` because in JSON schema for license vulnerabilities no `moduleName` is defined (only packageName)
- append `org` configuration parameter to URL if it's defined in configuration section
=> fix: missing package name for license vulns

README.md, pom.xml, src/it/settings.xml, src/main/java/io/snyk/maven/plugins/Constants.java, src/main/java/io/snyk/maven/plugins/SnykMonitor.java, src/main/java/io/snyk/maven/plugins/SnykTest.java
Adds a configuration parameter to fail the build if authentication fails, instead of just logging errors.
PR should be straightforward
Configure the plugin with failOnAuthError=true and run a build without setting the apiToken. The build should now fail.
Created this based on some discussions on our internal shared signicat-snyk slack channel. 
Ref: Eliran Cohen
Our ref: PLAT-164
N/A
N/A
The tests `-Prun-its` was failing before I started, and I did not spend time on why.
=> feat: New optional parameter, fail build if authentication fails

README.md, pom.xml, src/it/settings.xml, src/main/java/io/snyk/maven/plugins/SnykMonitor.java, src/main/java/io/snyk/maven/plugins/SnykTest.java
This PR logs response on debug level if snyk test or monitor failed.
=> feat: log response on debug level when request failed

README.md, pom.xml, src/it/settings.xml
This PR bumps plugin version to `1.2.9`, before releasing to Maven Central.
=> chore: bump plugin version to 1.2.9

pom.xml
We're using old versions of stuff from the plugin archetype. This causes issues when we're reading docs that mention features we don't have, such as invoker plugin's support for env vars in property files. So I've gone through and upgraded everything.
To check for latest versions, use http://www.mojohaus.org/versions-maven-plugin/
=> chore: upgrade dependency versions for v2

pom.xml
Sets the plugin pre-requisite minimum to Maven 3.1.0
Test project was failing to run from command line because of this.
=> Set minimum maven version prerequisite

src/main/java/io/snyk/snyk_maven_plugin/download/Platform.java
Removes VisibleForTesting annotations as it's not in dependencies and causes build issues on clean Maven installations. It works sometimes because some other project adds it to `.m2`. I don't think we need an entire dependency for this yet so I removed it entirely.
=> chore: remove annotation missing from deps

src/main/java/io/snyk/snyk_maven_plugin/AbstractSnykMojo.java, src/main/java/io/snyk/snyk_maven_plugin/command/CommandRunner.java, src/main/java/io/snyk/snyk_maven_plugin/download/CLIVersions.java, src/main/java/io/snyk/snyk_maven_plugin/download/ExecutableDownloader.java, src/test/java/io/snyk/snyk_maven_plugin/download/CLIVersionsTest.java
It's difficult to know where the behaviour to satisfy Maven lies so I've moved all exception handling up to the `execute` where it decides what's a MojoExecution and MojoFailure exception. No other class should be aware of Maven.
I've also reduced checked exception propagation noise using unchecked exceptions.
=> refactor: avoid leaking Maven details beyond MOJO

src/main/java/io/snyk/snyk_maven_plugin/AbstractSnykMojo.java
Removed global property assignments. If we do want to support specific properties, we probably want them namespaced and tested. (e.g. skipping)
Oddly, by not providing a property for `args`, Maven will set it to `null` rather than an empty `List`. So I've handled that.
=> fix: remove property assignments

pom.xml
Runs acceptance tests in parallel. In this case, if you have 16 cores, it'll run 8 tests at a time (`0.5 x C`). This cuts down test times from 1 minute to 30 seconds (on my laptop) so we can save on dev time. I used 0.5 to avoid over stressing the CPU which may be needed for other tasks. We'll see how GitHub Actions behaves with this PR.
The risk is introducing flakey tests but I don't think we have that problem. Only one test tests for auto-download (global state), the other global state is `.m2` which Maven can handle. In general we should avoid global state anyway so it's good to get this in early to detect issues.
=> chore: run acceptance tests in parallel

.github/workflows/test.yml
Currently we're downloading Maven deps on every test run in CI. That's wasteful so I've added a cache step.
Since we `mvn install` our plugin, this might cause false positives if say `mvn install` somehow fails without failing the build (unlikely without a bug in mvn) and the next steps use a previously cached plugin. Since it's unlikely I don't think it matters.
I also ran the YAML through Intellij as a separate commit for consistency. Might be easier to see the change by viewing the second commit.
=> chore: cache local maven repository in ci

src/main/java/io/snyk/snyk_maven_plugin/command/CommandLine.java, src/test/java/io/snyk/snyk_maven_plugin/command/CommandLineTest.java
We need the integration-name to separate executions via this plugin from direct CLI executions. Also, if an `--integration-name` arg is detected, it will be ignored. Though, I'm not 100% sure if we should fail or allow it so that's up for discussion.
I also added a step to normalise the args a bit by trimming whitespace to make detecting `--integration-name` easier.
=> feat: always include integration-name

src/it/test-skip-pom/invoker.properties, src/it/test-skip-pom/pom.xml, src/it/test-skip-pom/verify.groovy, src/it/test-skip-property/invoker.properties, src/it/test-skip-property/pom.xml, src/it/test-skip-property/verify.groovy, src/main/java/io/snyk/snyk_maven_plugin/AbstractSnykMojo.java
Adds a `skip` flag to pom configuration and `-Dsnyk.skip` support like the previous plugin (similar to Invoker plugins `invoker.skip`).
The Surefire plugin has a more global `-DskipTests` but not all plugins use this (like Invoker), [some do](http://maven.apache.org/plugins-archives/maven-surefire-plugin-2.12.4/examples/skipping-test.html). So I don't think we should either. Better to be explicitly skipped.
For testing, it's difficult to assert the command isn't executed as the CLI output can change and pass the test incorrectly. Maybe we can have a mock API endpoint which we can assert on to not have received requests. But this might require moving off the limited `verify.groovy` scripts.
=> feat: support skip flag in pom and properties

pom.xml
The 'prerequisites' config is deprecated and Maven 3 recommends using the Enforcer plugin instead.
https://maven.apache.org/pom.html#Prerequisites
https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
=> chore: use enforcer plugin to enforce min version

README.md, src/it/monitor-with-default-phase/invoker.properties, src/it/monitor-with-default-phase/pom.xml, src/it/monitor-with-default-phase/verify.groovy, src/it/test-with-default-phase/invoker.properties, src/it/test-with-default-phase/pom.xml, src/it/test-with-default-phase/verify.groovy, src/main/java/io/snyk/snyk_maven_plugin/goal/SnykMonitorMojo.java, src/main/java/io/snyk/snyk_maven_plugin/goal/SnykTestMojo.java
As we already recommend using `test` and `monitor` in specific phases, I've removed that setup step in favour of using sane defaults. Support for overriding  the default phase is standard Maven behaviour so we don't need to document it.
=> feat: use recommended phases as default

README.md
Didn't contain the actual executable which is misleading as downloadDestination requires the full path.
Also added links for Maven Centrals, formatting, and fixed typos.
=> docs: correct default downloadDestination and inheritance config

README.md
`critical` is not a valid value.
=> docs: use an available value for severity example

.circleci/config.yml, .github/workflows/test.yml, pom.xml, src/it/test-code-test/verify.groovy, src/it/test-with-ignores/.snyk
* Updates state assertions in line with latest data. Ideally these tests should be more resilient to changing data state but that work is out of scope for the current task.
* Updated GitHub action to more recent versions to remove deprecated warning in Action summary
* Skip test directory as part of Snyk scans which was resulting in false positives
* Skip consistently failing container test on Windows. Suspected cause is limited toolchain on windows image. Further investigation required, which is out of scope for the current task. 
* Mitigate https://app.snyk.io/vuln/SNYK-JAVA-ORGAPACHEMAVEN-6144614 by upgrading
maven-core to 3.8.1.
=> chore: address failures in CI pipeline

CONTRIBUTING.md
Updates the contributing.md with new release steps
=> chore(docs): update contributing.md
